#################################################
# Makefile
#################################################

#job-centos8-makefile-gcc:
#
#  tags: [ "docker" ]
#  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-centos8:$CENTOS_8_IMAGE_VERSION
#  except:
#    variables:
#      - $DEPLOY_RUN
#      - $DEPLOY_UBUNTU
#  variables:
#    CMAKE_GENERATOR: Unix Makefiles
#    CMAKE_OPTIONS: -DINTERNAL_LIBSRTP2=ON
#    CC: gcc
#    CXX: g++
#  extends: .job-linux-nightly
#
#job-centos8-makefile-clang:
#
#  tags: [ "docker" ]
#  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-centos8:$CENTOS_8_IMAGE_VERSION
#  except:
#    variables:
#      - $DEPLOY_RUN
#      - $DEPLOY_UBUNTU
#  variables:
#    CMAKE_GENERATOR: Unix Makefiles
#    CMAKE_OPTIONS: -DINTERNAL_LIBSRTP2=ON
#    CC: clang
#    CXX: clang++
#  extends: .job-linux

#################################################
# Ninja
#################################################

job-centos8-ninja-gcc:
  extends: .job-linux-nightly

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-centos8:$CENTOS_8_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON -DINTERNAL_LIBSRTP2=ON
    CC: gcc
    CXX: g++

job-centos8-ninja-clang:
  extends:
    - .job-linux
    - .rules-dev  # ⚠ See `rules.yml`

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-centos8:$CENTOS_8_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON -DINTERNAL_LIBSRTP2=ON
    CC: clang
    CXX: clang++

#################################################
# RPM
#################################################

job-centos8-rpm:
  allow_failure: true
  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-centos8:$CENTOS_8_IMAGE_VERSION
  variables:
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON -DINTERNAL_LIBSRTP2=ON
  extends: .job-linux-rpm

job-centos8-rpm-deploy:
  extends: .rules-deploy  # ⚠ See `rules.yml`

  stage: deploy
  tags: [ "deploy" ]

  dependencies:
    - job-centos8-rpm

  script: ./.gitlab-ci-files/deploy.sh centos

