#################################################
# Makefile
#################################################

job-ubuntu-18.04-makefile-gcc:

  tags: [ "docker-ubuntu-18.04" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-18-04-lts:$UBUNTU_18_04_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON
    CC: gcc
    CXX: g++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .scheduled-job-linux


job-ubuntu-18.04-makefile-clang:

  tags: [ "docker-ubuntu-18.04" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-18-04-lts:$UBUNTU_18_04_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON
    CC: clang
    CXX: clang++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .scheduled-job-linux

#################################################
# Ninja
#################################################

job-ubuntu-18.04-ninja-gcc:

  tags: [ "docker-ubuntu-18.04" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-18-04-lts:$UBUNTU_18_04_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Ninja
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON
    CC: gcc
    CXX: g++
  extends: .job-linux


job-ubuntu-18.04-ninja-clang:

  tags: [ "docker-ubuntu-18.04" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-18-04-lts:$UBUNTU_18_04_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Ninja
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON
    CC: clang
    CXX: clang++
  extends: .scheduled-job-linux
  
#################################################
# DEB
#################################################

job-ubuntu-18.04-deb:

  tags: [ "docker-ubuntu-18.04" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-18-04-lts:$UBUNTU_18_04_IMAGE_VERSION
  extends: .job-linux-deb
  only:
    - schedules
  variables:
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON



job-ubuntu-18.04-deb-deploy:

  variables:
    RELEASE: bionic
    FREIGHT_PATH: $UBUNTU_FREIGHT_CONF_PATH
  extends: .job-debian-deb-deploy
  dependencies:
    - job-ubuntu-18.04-deb
