#################################################
# Makefile
#################################################

job-debian9-makefile-gcc:

  tags: [ "docker-debian9" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON
    CC: gcc
    CXX: g++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .scheduled-job-linux


job-debian9-makefile-clang:

  tags: [ "docker-debian9" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON
    CC: clang
    CXX: clang++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .scheduled-job-linux

#################################################
# Ninja
#################################################

job-debian9-ninja-gcc:

  tags: [ "docker-debian9" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Ninja
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON
    CC: gcc
    CXX: g++
  extends: .scheduled-job-linux


job-debian9-ninja-clang:

  tags: [ "docker-debian9" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Ninja
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON
    CC: clang
    CXX: clang++
  extends: .job-linux


#################################################
# DEB
#################################################

job-debian9-deb:

  tags: [ "docker-debian9" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  extends: .job-linux-deb
  except:
    variables:
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON


job-debian9-deb-deploy:

  except:
    variables:
      - $DEPLOY_UBUNTU
  variables:
    RELEASE: stretch
    FREIGHT_PATH: $DEBIAN_FREIGHT_CONF_PATH
  extends: .job-debian-deb-deploy
  dependencies:
    - job-debian9-deb


#################################################
# Docker
#################################################

job-flexisip-debian9-image-deploy:

  dependencies:
    - job-debian9-deb
  extends: .job-flexisip-image-deploy
